[project]
name = 'Blockchain-Enabled-Historic-Artifact-Provenance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.artifact-registration]
path = 'contracts/artifact-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.authentication-verification]
path = 'contracts/authentication-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
